openapi: 3.0.1
info:
  title: coffee-user-svc API
  version: 1.0.0
servers:
- url: "http://{{base_url}}"
paths:
  /health:
    get:
      summary: Get Health
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  message:
                    type: string
  /user_{userId}:
    get:
      summary: Get User By Id
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      password:
                        type: string
    put:
      summary: Update User By Id
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                name:
                  type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
      x-codegen-request-body-name: body
    delete:
      summary: Delete User By Id
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: string
  /exists/{email}:
    get:
      summary: Does User Exist
      parameters:
      - name: email
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: boolean
  /:
    post:
      summary: Add new User
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      password:
                        type: string
  /authenticate:
    post:
      summary: Authenticate User
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      isAuthenticated:
                        type: boolean
                      name:
                        type: string
                      email:
                        type: string
                      userId:
                        type: string
components: {}
x-original-swagger-version: "2.0"
